name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update stable
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Install cargo-nextest
      uses: taiki-e/install-action@cargo-nextest
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo llvm-cov nextest --workspace --all-features
